name: "Run gitleaks with config located in another remote repo"
on: [push, pull_request]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy external config to main repo & cd to main
        run: |
          git clone https://${secrets.ACCESS_TOKEN}:x-oauth-basic@github.com/vgaidarji/gitleaks-sample-config.git external-config
          cp external-config/.gitleaks.toml .
          ls -al
          echo "Workspace dir $GITHUB_WORKSPACE"
      - name: List files in current dir
        run: |
          ls -al
          echo "Printing the gitleaks config to be used"
          echo "We want to make sure it's not matching the one predefined in gitleaks action https://github.com/zricethezav/gitleaks-action/blob/master/.gitleaks.toml"
          cat $GITHUB_WORKSPACE/.gitleaks.toml
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
