name: "Run gitleaks with config located in another remote repo"
on: [push, pull_request]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout remote gitleaks config
        uses: actions/checkout@v2
        with:
            repository: vgaidarji/gitleaks-sample-config
            token: ${{ secrets.ACCESS_TOKEN }} 
            path: external-config
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: main
      - name: Copy external config to main repo & cd to main
        run: |
          cp external-config/.gitleaks.toml main/.gitleaks.toml
          cd main
          ls -al
          echo "Workspace dir $GITHUB_WORKSPACE"
      - name: List files in current dir
        run: |
          ls -al
          echo "Printing the gitleaks config to be used"
          echo "We want to make sure it's not matching the one predefined in gitleaks action https://github.com/zricethezav/gitleaks-action/blob/master/.gitleaks.toml"
          cat $GITHUB_WORKSPACE/.gitleaks.toml
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
